In [1]:
#importing libraries 
import numpy as np
import pandas as pd
import math
import sympy as sym
from sympy import symbols, exp
import sys
import scipy
import scipy.linalg as la
import numpy.linalg as nu
from numpy.linalg import matrix_power as mpow
np.set_printoptions(precision=10)
np.set_printoptions(suppress=True)

In [2]:
def cra(matA,v_0):
    n = matA.shape[0]
    u = np.full((n,1),0,dtype = float) 
    d = det(matA)
    if d == 0 :
        print('Unexpected singular matrix');
        sys.exit()
    for i in range(n):
        dx = np.delete(matA,i,1)
        dx = np.concatenate((dx, v_0), axis=1)
        u[i][0] = pow(-1,i+n-1)*(nu.det(dx))/d
    return u

In [3]:
def Gau_Sed(matA,matb,u):
    n = matA.shape[0]
    while norm(matA,u,matb) > 1e-5:       #while function running till the norm converge
        
        
        #basic arithmatic logic for Gauss Siedel method 
        for i in range(n):
            f = 0
            for j in range(n):
                f = f  + matA[i][j] * u[j][0]
            r = matb[i][0] - f
            if matA[i][i] == 0 :
                print("Unexpected 0 pivot");
                sys.exit()
            u[i][0] = u[i][0] + r/matA[i][i]
            r = 0
            print(norm(matA,u,matb))
           
        
        #Check if the matrix in diverging 
        if norm(matA,u,matb) > 1e10:
            break;
            print('Oops matrix did not converge');
            sys.exit()
    return u

In [4]:
def NewRap(eqn,diff,guess,max_error):
    x1 = guess;
    while abs((eqn.subs(x,x1)).evalf()) > max_error:         #running the loop till it converges below max_error
        x2 =  x1 - eqn.subs(x,x1)/diff.subs(x,x1);            #calculating the next x
        x1 =  x2.evalf()                                #initialising the next value to prev value for next loop
    return x1

In [5]:
a = np.array([[1,2],[2,1]])
a

array([[1, 2],
       [2, 1]])

In [6]:
nu.norm(a)

3.1622776601683795

In [7]:
a = np.array([[1, 0, 0],[0 , 5, 0], [1 ,1 ,6 ]])
a

array([[1, 0, 0],
       [0, 5, 0],
       [1, 1, 6]])

In [8]:
c = np.array([[2,3,1],[0,2,0],[0,0,1]])
c

array([[2, 3, 1],
       [0, 2, 0],
       [0, 0, 1]])

In [9]:
#eigen value 
nu.eigvals(a)

array([6., 1., 5.])

In [10]:
nu.eig(a)

(array([6., 1., 5.]),
 array([[ 0.          ,  0.9805806757,  0.          ],
        [ 0.          ,  0.          ,  0.7071067812],
        [ 1.          , -0.1961161351, -0.7071067812]]))

In [11]:
nu.eig(a@a)

(array([36.,  1., 25.]),
 array([[ 0.          ,  0.9805806757,  0.          ],
        [ 0.          ,  0.          ,  0.7071067812],
        [ 1.          , -0.1961161351, -0.7071067812]]))

In [12]:
la.eig(a)

(array([6.+0.j, 1.+0.j, 5.+0.j]),
 array([[ 0.          ,  0.9805806757,  0.          ],
        [ 0.          ,  0.          ,  0.7071067812],
        [ 1.          , -0.1961161351, -0.7071067812]]))

In [13]:
nu.det(a)

29.99999999999999

In [14]:
k = nu.inv(a)
k

array([[ 1.          ,  0.          ,  0.          ],
       [ 0.          ,  0.2         ,  0.          ],
       [-0.1666666667, -0.0333333333,  0.1666666667]])

In [15]:
k@c@a

array([[ 3.          , 16.          ,  6.          ],
       [ 0.          ,  2.          ,  0.          ],
       [-0.3333333333, -2.8333333333,  0.          ]])

In [16]:
a = np.array([[2.11, -4.21, 0.921],[4.01 , 10.2, -1.12], [1.09 ,0.987 ,0.0832 ]])
a

array([[ 2.11  , -4.21  ,  0.921 ],
       [ 4.01  , 10.2   , -1.12  ],
       [ 1.09  ,  0.987 ,  0.0832]])

In [17]:
c = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
c

array([[ 2, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  2]])

In [18]:
#create the u matrix for storing the guess value
v = np.array([[0],[0],[0]])
v

array([[0],
       [0],
       [0]])

In [19]:
c = np.array([[1,-2,3],[1,2,1],[-1,2,-3]])
c

array([[ 1, -2,  3],
       [ 1,  2,  1],
       [-1,  2, -3]])

In [20]:
nu.det(c)

0.0

# Q5

In [21]:
import control as con
from control.matlab import *

In [22]:
A = np.array([[1,0,0],[2,-2,0],[0,1,-3]])
B =  np.array([[0],[1],[2]])
C =  np.array([[0, 1, 2]])
D = np.array([0])

In [23]:
sys = StateSpace(A,B,C,D)
sys

StateSpace(array([[ 1.,  0.,  0.],
       [ 2., -2.,  0.],
       [ 0.,  1., -3.]]), array([[0.],
       [1.],
       [2.]]), array([[0., 1., 2.]]), array([[0.]]))

In [24]:
def Qm(A):
    if A.shape[0] == 2:
        return np.concatenate((B,A@B),axis = 1)
    elif A.shape[0] == 3:
        return np.concatenate((np.concatenate((B,A@B),axis = 1),A@A@B),axis = 1)

In [25]:
Q = Qm(A)
Q

array([[ 0,  0,  0],
       [ 1, -2,  4],
       [ 2, -5, 13]])

In [26]:
nu.eig(Q)

(array([11.5207972894, -0.5207972894,  0.          ]),
 array([[0.          , 0.          , 0.762000762 ],
        [0.2836865454, 0.9379226701, 0.635000635 ],
        [0.9589170684, 0.346844439 , 0.127000127 ]]))

In [27]:
P = np.delete(Q,2,1)

inp = np.array([[8],[5],[1]])

P = np.concatenate((P,inp),axis = 1)
P

array([[ 0,  0,  8],
       [ 1, -2,  5],
       [ 2, -5,  1]])

In [28]:
nu.eig(P)

(array([-1.1211109778+0.j          ,  0.0605554889+2.6706014078j,
         0.0605554889-2.6706014078j]),
 array([[ 0.9383930562+0.j          ,  0.8301626146+0.j          ,
          0.8301626146-0.j          ],
        [ 0.3195697365+0.j          ,  0.4812660301+0.048713159j ,
          0.4812660301-0.048713159j ],
        [-0.1315053446+0.j          ,  0.0062838629+0.2771291809j,
          0.0062838629-0.2771291809j]]))

In [29]:
Pi = nu.inv(P)
Pi

array([[-2.875,  5.   , -2.   ],
       [-1.125,  2.   , -1.   ],
       [ 0.125,  0.   ,  0.   ]])

In [30]:
Ans1 = Pi@A@P
Ans1

array([[ 0., -6.,  3.],
       [ 1., -5.,  1.],
       [ 0.,  0.,  1.]])

In [31]:
Ans2 = Pi@B
Ans2

array([[1.],
       [0.],
       [0.]])

In [32]:
Ac = np.array([[0,-6],[1,-5]])
Bc = np.array([[1,0]])

In [33]:
nu.eig(Ac)

(array([-2., -3.]),
 array([[0.9486832981, 0.894427191 ],
        [0.316227766 , 0.4472135955]]))

In [34]:
k1 = symbols('k1') 
k2 = symbols('k2') 
kc = np.array([[k1,k2]])
kc

array([[k1, k2]], dtype=object)

In [35]:
nu.eig(Ac - Bc@kc)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

# 2D

In [90]:
A = np.array([[2,3],[0,-2]])
B =  np.array([[1],[0]])
C =  np.array([[1, 1]])
D = np.array([0])

In [91]:
sys = StateSpace(A,B,C,D)
sys

StateSpace(array([[ 2.,  3.],
       [ 0., -2.]]), array([[1.],
       [0.]]), array([[1., 1.]]), array([[0.]]))

In [92]:
nu.eig(A)

(array([ 2., -2.]),
 array([[ 1. , -0.6],
        [ 0. ,  0.8]]))

In [93]:
Q = Qm(A)
Q

array([[1, 2],
       [0, 0]])

In [94]:
nu.eig(Q)

(array([1., 0.]),
 array([[ 1.          , -0.894427191 ],
        [ 0.          ,  0.4472135955]]))

In [95]:
P = np.delete(Q,1,1)

inp = np.array([[6],[5]])

P = np.concatenate((P,inp),axis = 1)
P

array([[1, 6],
       [0, 5]])

In [96]:
nu.eig(P)

(array([1., 5.]),
 array([[1.          , 0.8320502943],
        [0.          , 0.5547001962]]))

In [97]:
Pi = nu.inv(P)
Pi

array([[ 1. , -1.2],
       [ 0. ,  0.2]])

In [98]:
Ans1 = Pi@A@P
Ans2 = Pi@B

In [99]:
Ac = np.array([[-2]])
Bc = np.array([[6]])

In [100]:
k = np.array([[k1,k2]])
k

array([[k1, k2]], dtype=object)

In [101]:
d = A - B@k
d

array([[2 - k1, 3 - k2],
       [0, -2]], dtype=object)

#  Hecker men formula for 2D

In [102]:
# 2 D
A = np.array([[1,1],[0,1]])
B =  np.array([[0],[1]])
C =  np.array([[1, 1]])
D = np.array([0])

In [103]:
sys = StateSpace(A,B,C,D)
sys

StateSpace(array([[1., 1.],
       [0., 1.]]), array([[0.],
       [1.]]), array([[1., 1.]]), array([[0.]]))

In [104]:
Qc = Qm(A)
Qc

array([[0, 1],
       [1, 1]])

In [105]:
nu.eig(Qc)

(array([-0.6180339887,  1.6180339887]),
 array([[-0.8506508084, -0.5257311121],
        [ 0.5257311121, -0.8506508084]]))

In [106]:
Qci = nu.inv(Qc)
Qci

array([[-1.,  1.],
       [ 1.,  0.]])

In [107]:
lem1 = -1 
lem2 = -2

In [108]:
phi = lem1*lem2*np.eye(2) + -1*(lem1+lem2) * A + A@A
phi

array([[6., 5.],
       [0., 6.]])

In [109]:
K = np.array([[0,1]]) @ Qci @ phi
K

array([[6., 5.]])

In [112]:
A = np.array([[1,2,0],[0,-1,0],[0,1,1]])

In [113]:
nu.eig(A)

(array([ 1.,  1., -1.]),
 array([[ 1.          ,  0.          , -0.6666666667],
        [ 0.          ,  0.          ,  0.6666666667],
        [ 0.          ,  1.          , -0.3333333333]]))

In [51]:
A = np.array([[1,2,0],[0,1,0],[0,0,1]])


In [52]:
P = np.array([[1,1,0],[0,0.5,0],[0,0,1]])
P

array([[1. , 1. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 1. ]])

In [53]:
Pi = nu.inv(P)
Pi

array([[ 1., -2.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  1.]])

In [54]:
Pi@A@P

array([[1., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

New rap

In [ ]:
#Newton raphson
x = symbols('x')
fun =  sym.cos(x)
diff = (sym.sin(x)) * -1;
guess = 0.785398;
x1 = guess;