In [12]:
import numpy as np
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [13]:
def R1(z):
    y = np.radians(z)
    x = np.empty([3,3])
    x[0,0] = 1
    x[0,1] = 0
    x[0,2] = 0
    x[1,0] = 0
    x[1,1] = np.cos(y)
    x[1,2] = -np.sin(y)
    x[2,0] = 0
    x[2,1] = np.sin(y)
    x[2,2] = np.cos(y)
    return x

def R2(z):
    y = np.radians(z)
    x = np.empty([3,3])
    x[0,0] = np.cos(y)
    x[0,1] = 0
    x[0,2] = np.sin(y)
    x[1,0] = 0
    x[1,1] = 1
    x[1,2] = 0
    x[2,0] = -np.sin(y)
    x[2,1] = 0
    x[2,2] = np.cos(y)
    return x

def R3(z):
    y = np.radians(z)
    x = np.empty([3,3])
    x[0,0] = np.cos(y)
    x[0,1] = -np.sin(y)
    x[0,2] = 0
    x[1,0] = np.sin(y)
    x[1,1] = np.cos(y)
    x[1,2] = 0
    x[2,0] = 0
    x[2,1] = 0
    x[2,2] = 1
    return x
def A(r1,r2):
    return np.matmul(r1,r2)
def tr(r1):
    return np.trace(r1)

In [14]:
R1(30)

array([[ 1.   ,  0.   ,  0.   ],
       [ 0.   ,  0.866, -0.5  ],
       [ 0.   ,  0.5  ,  0.866]])

In [15]:
np.cos(np.pi/2)

6.123233995736766e-17

In [16]:
r1 = R1(30)
r1



array([[ 1.   ,  0.   ,  0.   ],
       [ 0.   ,  0.866, -0.5  ],
       [ 0.   ,  0.5  ,  0.866]])

In [17]:
r2 = R2(30)
r2

array([[ 0.866,  0.   ,  0.5  ],
       [ 0.   ,  1.   ,  0.   ],
       [-0.5  ,  0.   ,  0.866]])

In [18]:
r3 = R3(30)
r3

array([[ 0.866, -0.5  ,  0.   ],
       [ 0.5  ,  0.866,  0.   ],
       [ 0.   ,  0.   ,  1.   ]])

In [19]:
R1(30),R2(30),R3(30)

(array([[ 1.   ,  0.   ,  0.   ],
        [ 0.   ,  0.866, -0.5  ],
        [ 0.   ,  0.5  ,  0.866]]),
 array([[ 0.866,  0.   ,  0.5  ],
        [ 0.   ,  1.   ,  0.   ],
        [-0.5  ,  0.   ,  0.866]]),
 array([[ 0.866, -0.5  ,  0.   ],
        [ 0.5  ,  0.866,  0.   ],
        [ 0.   ,  0.   ,  1.   ]]))

In [20]:
r8 = A(r1,r2)
r8

array([[ 0.866,  0.   ,  0.5  ],
       [ 0.25 ,  0.866, -0.433],
       [-0.433,  0.5  ,  0.75 ]])

In [21]:
tr(r8)

2.4820508075688776

# Exam

In [22]:
c = np.array([[11,4,0],[4,5,0],[0,0,7]])

In [23]:
r1@c@np.transpose(r1)

array([[11.    ,  3.4641,  2.    ],
       [ 3.4641,  5.5   , -0.866 ],
       [ 2.    , -0.866 ,  6.5   ]])